### ISSUE TITLE
Departed ferries shown half empty when long queue present?

### ISSUE THREAD

**Issue by mileserickson** [anstosa/ferry.fyi#17]

**Comment by mileserickson** [comment]
![IMG_1994](https://user-images.githubusercontent.com/68300/61649183-d3681980-ac65-11e9-9c93-b9cff97b1530.PNG)

**Comment by mileserickson** [comment]
This might require some attention (and will be easier to validate if we can run some simple ML on the camera images): when I saw that boats were leaving Clinton half-empty last night, I headed to the ferry, only to find that the line was backed up past the 90 minute sign.

**Comment by mileserickson** [comment]
Specifically:

At 7:35 p.m. on Sunday 7/21, I was waiting in a queue for the Clinton ferry (on the Whidbey side) that was backed up to the 90 minute sign. The site alleges that the 7:35 p.m. ferry departed with 45 empty spaces. This seems implausible.

**Comment by anstosa** [comment]
Yeah those boats were definitely full. Not sure what happened here. There were a couple temporary API outages yesterday which may have contributed. I also have a suspicion that it has something to do with us having the Kitsap (and it's much reduced capacity) this week. The capacities were reported correctly but I'm not sure what mechanism they're using on-site to report those numbers and maybe something got screwed up in the math.

This is more of a fun fact but the numbers are also much fuzzier than I expected. For example, the Suquamish's capacity as reported by the tollbooth is 145, but the vessel stats report a total capacity of 178 and a "tall vehicle capacity" of 34. So basically, if there is anything less than a full load of overheight vehicles, the boats will all take more cars than advertised (plus the inherent fuzziness of the fact that both of those numbers are assuming some unnamed average vehicle length)

**Comment by anstosa** [comment]
tl:dr; because this is the first time I've seen a capacity count that's clearly wrong, I'm going to chalk this up to one of the several anomalies on the day for this route but I'll keep the ticket open for now and keep and eye of things to make sure this doesn't recur.

**Possible Mitigations**
* Use CV data to validate API data
* User some common sense heuristics to validate API data (e.g. reported data deviates by some amount from the capacity curve we expect based on historical data).

Questionable data should be flagged in the UI for the user

**Comment by anstosa** [comment]
Since this is happening today, I think I have more clarity on the issue. WSF only reports real-time capacity for the "next" boat on the schedule. However, their version of "next" isn't really accurate. Currently it's 5:07 and it's listing the next departure from Mukilteo as 5:10 even though the 4:40 hasn't left yet because the boats are 42mins behind.

I'm guessing the last snapshot of the capacity we get is when it passes the 30min delay mark because it switches to the next sailing automatically. When this happens, we should assume the previous sailing is full
