### ISSUE TITLE
"Punctuality Unknown" all sailings Muk/Clinton

### ISSUE THREAD

**Issue by mileserickson** [anstosa/ferry.fyi#18]
![54C84681-B93E-4C56-A4E6-B85D8D0E08CA](https://user-images.githubusercontent.com/68300/61963335-33b9cc80-af80-11e9-8fbb-718b562babaf.png)

Unclear what's going on here. VesselWatch is up, so it doesn't appear to be a WSF outage.

![3ACC616D-1CCB-455B-819D-504542703F33](https://user-images.githubusercontent.com/68300/61963524-a3c85280-af80-11e9-8871-cec86b537bc6.jpeg)

**Comment by anstosa** [comment]
I think there is a bug in my end that I'm not getting delay information even though it appears on VesselWatch, but if you click through to a terminal in vessel watch you'll see the the real-time schedule including vehicle count reporting is down and has been since the WSF website maintenance yesterday. I reported it to them yesterday and am keeping an eye on it

**Comment by anstosa** [comment]
API service is fully restored and I have fix the issue causing a ton of "punctuality unknown"s
